


# Permalinks
permalink:        pretty

# Setup
title:            HMT twiddle
tagline:          'Scripting the Homer Multitext archive'
description:      'A Scala environment for interactive work with HMT project data sets'


baseurl: '/hmt-twiddle/'


author:
  name:           'Neel Smith'


links:
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: HMT web
    url: http://homermultitext.org/
    external: true
