


# Permalinks
permalink:        pretty

# Setup
title:            HMT twiddle
tagline:          ''
description:      ''


baseurl: '/hmt-twiddle/'


author:
  name:           'Neel Smith'


links:
  - title: Schedule
    url:  /schedule
  - title: Current score!
    url:  /score
  - title: Images of the manuscript
    url:  /thumbs
  - title: References for editors
    url:  /references
  - title: Hackathon home page
    url:  /
  - title: Further projects
    url:  /next
  - title: HC MID club
    url: http://hcmid.github.io/
    external: true
  - title: Acknowledgments
    url: gratias
